### PR TITLE
Fix validation of relationship serialisation

### LINKED ISSUE #84: Fix serialisation validation
In the course of https://github.com/wopian/kitsu/pull/81 it came up that `serialise` doesn't validate data correctly: https://github.com/wopian/kitsu/pull/81#issuecomment-354578586

Do we need different validation logic for different methods (POST/PATCH/PUT?) or is it the same for all?

### PR DESCRIPTION
**Pull request by duk3luk3**
Removes alternative check for type attribute on relationship elements.

The check is superfluous, ID check is necessary.

Fixes #84.

### CODE REVIEW

File: src/util/serialise/index.js [hunk 1]
```diff
@@ -28,29 +28,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
...
-        // Guess relationship type if not provided
-        if (typeof obj[prop].type === 'undefined') obj[prop].type = this.plural(this.camel(prop))
-        data.relationships[prop] = { data: Object.assign(obj[prop]) }
+        if (typeof obj[prop].id === 'string') {
+          if (typeof data.relationships === 'undefined') data.relationships = {}
+          // Guess relationship type if not provided
+          if (typeof obj[prop].type === 'undefined') obj[prop].type = this.plural(this.camel(prop))
+          data.relationships[prop] = { data: Object.assign(obj[prop]) }
+        } else {
+          throw new Error(`${method} requires an ID for the ${prop} relationships`)
```
Comment (wopian) [inline src/util/serialise/index.js]: Can this be `} else throw new Error(...)`

File: src/util/serialise/index.js [hunk 2]
```diff
@@ -28,29 +28,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
...
+        }
+      // Check if it's a relationship array
       } else if (
         obj[prop] !== null &&
         obj[prop].constructor === Array
```
Comment (wopian) [inline src/util/serialise/index.js]: these conditions can be on one line too

File: src/util/serialise/index.js [hunk 3]
```diff
@@ -28,29 +28,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
...
     for (let prop in obj) {
-      // Check if its a relationship
+      // Check if it's a relationship
       if (
         obj[prop] !== null &&
-        obj[prop].constructor === Object && (
-          typeof obj[prop].id === 'string' ||
-          typeof obj[prop].type === 'string'
-        )
+        obj[prop].constructor === Object
```
[the remark this answers is not in the document]
Comment (duk3luk3) [reply src/util/serialise/index.js]: I don't see how to merge those conditions and still maintain correct control flow, since it would run into the `else if (prop !== 'id')` branch and assume it's an attribute.

[the remark this answers is not in the document]
Comment (wopian) [reply src/util/serialise/index.js]: Sorry I mean't

```js
if  (!== null && Object)
```

instead of the current

```js
if (
  !== null &&
  Object
)
```

File: src/util/serialise/index.js [hunk 4]
```diff
@@ -28,29 +28,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
...
         const ptype = this.plural(this.camel(prop))
         for (var i = 0; i < obj[prop].length; i++) {
-          if (
-            typeof obj[prop][i].id === 'string' ||
-            typeof obj[prop][i].type === 'string'
-          ) {
+          if (typeof obj[prop][i].id === 'string') {
             // Guess relationship type if not provided
             if (typeof obj[prop][i].type === 'undefined') obj[prop][i].type = ptype
           } else {
```
Comment (wopian) [inline src/util/serialise/index.js]: [Merging](https://github.com/wopian/kitsu/pull/85/files/a6dd34c2c1283c04aa157fb74ffa095aa6fd1966#r159580574) the `typeof id` and `typeof type` conditions will work if we check `id` is undefined before throwing the missing ID error.

```js
else if (typeof obj[prop][i].id === 'undefined')
```

**Comment by duk3luk3** [comment]
I turned the for loop into a map as we initially wanted to do. Does this look good to you?

**Comment by wopian** [comment]
Awesome! Thanks for all of these fixes @duk3luk3 🎉

**Comment by duk3luk3** [comment]
Excellent, thanks for the quick response and review!

Are you going to push a release with this included soon?

**Comment by wopian** [comment]
`4.1.0` has been released 😃
