### PR TITLE
fix: handle relationship arrays (fixes #80)

### LINKED ISSUE #80: Serialising relationship arrays is not handled
Trying to post this with kitsu:

```
    container_users = container_users.map(x => ({
        id: x,
        type: 'users'
    }));

    api.create('container', {
        name: container_name,
        'creator': {
            'id': container_creator,
            'type': 'users'
        },
        'host': {
            'id': container_host,
            'type': 'hosts'
        },
        'users': container_users
    }).then(res => console.log(res)
    ).catch((reason) => console.log(reason));

```

results in this being POSTed:

```
{
  "data": {
    "type": "containers",
    "attributes": {
      "name": "testcontainer3",
      "users": [
        {
          "id": 1,
          "type": "users"
        },
        {
          "id": 2,
          "type": "users"
        }
      ]
    },
    "relationships": {
      "creator": {
        "data": {
          "id": 1,
          "type": "users"
        }
      },
      "host": {
        "data": {
          "id": 1,
          "type": "hosts"
        }
      }
    }
  },
  "headers": {
    "Authorization": "foobar",
    "accept": "application\/vnd.api+json",
    "content-type": "application\/vnd.api+json"
  }
}
```

it puts `users` into attributes instead of relationships, where it should go.

This is because the [relationship test](https://github.com/wopian/kitsu/blob/master/src/util/serialise.js#L35) in `serialise.js` does not test for arrays.

### PR DESCRIPTION
**Pull request by duk3luk3**
Adds a spec for #80 and a new serialiser code branch that fixes the issue.

### CODE REVIEW

**Comment by wopian** [comment]
Pushed fixes to the `serialise` specs to properly fail on async failures

**Comment by duk3luk3** [comment]
So, I've fixed the issue (insofar as the spec passes now), including validating and type-guessing for every array element, but it's pretty darn ugly.

It also needs better error handling.

Any idea how to make it nicer?

File: src/util/serialise.js [hunk 1]
```diff
@@ -43,6 +43,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
         // Guess relationship type if not provided
         if (typeof obj[prop].type === 'undefined') obj[prop].type = plural(camel(prop))
         data.relationships[prop] = { data: Object.assign(obj[prop]) }
+      } else if (
+        obj[prop] !== null &&
+        obj[prop].constructor === Array
+      ) {
+        // validate whole array
+        const ptype = plural(camel(prop))
+        for (var i = 0; i < obj[prop].length; i++) {
```
Comment (wopian) [inline src/util/serialise.js]: Can this `for` loop be replaced with a `forEach`:

```js
obj[prop].forEach(item => {
  if (typeof item.id === 'string')
})
```

File: src/util/serialise.js [hunk 2]
```diff
@@ -43,6 +43,28 @@ export async function serialise (model, obj = {}, method = 'POST') {
...
+          if (
+            typeof obj[prop][i].id === 'string' ||
+            typeof obj[prop][i].type === 'string'
+          ) {
+            // Guess relationship type if not provided
+            if (typeof obj[prop][i].type === 'undefined') obj[prop][i].type = ptype
+          } else {
+            // XXX: Better error handling?
+            // prop is not a valid relationship entry object
+            console.log('Invalid relationship prop')
```
Comment (wopian) [inline src/util/serialise.js]:
```js
throw new Error(`${method} requires an ID for the ${prop} relationships`)
```

File: src/util/serialise.js (hunk 1 above)
Comment (duk3luk3) [reply src/util/serialise.js]: I want to mutate the array element (writing the type, in line 54 below) in the loop, is it good practice to do that inside a forEach loop?

Comment (wopian) [reply src/util/serialise.js]: Shouldn't review things when I'm half asleep :laughing:

Should be a `map` instead of `forEach` in this case, Can leave it as it is now - i'll do it while cleaning up all the utility functions 👍

**Comment by duk3luk3** [comment]
Upon writing the spec for the error case, I got a little confused.

The control flow doesn't really make that much sense:

```js
          if (
            typeof obj[prop][i].id === 'string' ||
            typeof obj[prop][i].type === 'string'
          ) {
            // Guess relationship type if not provided
            if (typeof obj[prop][i].type === 'undefined') obj[prop][i].type = ptype
          } else {
            throw new Error(`${method} requires an ID for the ${prop} relationships`)
          }

```

"If not either id exists and is a string, or type exists and is a string, throw error about missing id"... shouldn't "missing type" and "missing id" be two separate cases, one leading to guessing the type, and one leading to error?

**Comment by wopian** [comment]
I think this was erroneously copied from the top level logic when I first wrote this last year:
- `type` can be missing and will be guessed from the `model` (endpoint)
- `id` is not used for `POST` requests

`POST` requests can't create [new resources](http://jsonapi.org/format/#crud-creating) inside its relationship object, only linking to existing resources. 👍 for splitting it into 2 cases.

**Comment by duk3luk3** [comment]
Can we do that later? :-)

(Also, happy new year and thank you for this great library!)

**Comment by wopian** [comment]
Happy new year 🎉
